---
- name: Configure Windows Server 2022
  hosts: all
  gather_facts: yes
  tasks:
    - name: Enable Remote Desktop
      win_service:
        name: TermService
        start_mode: auto
        state: started

    - name: Enable Remote Desktop through firewall
      win_firewall_rule:
        name: "Remote Desktop"
        enable: yes
        direction: in
        action: allow
        localport: 3389
        protocol: TCP

    - name: Disable Windows Firewall Domain Profile
      win_firewall_rule:
        name: "Domain Profile"
        enable: no
        direction: in
        action: block
        localport: all
        protocol: all

    - name: Disable Windows Firewall Private Profile
      win_firewall_rule:
        name: "Private Profile"
        enable: no
        direction: in
        action: block
        localport: all
        protocol: all

    - name: Disable Windows Firewall Public Profile
      win_firewall_rule:
        name: "Public Profile"
        enable: no
        direction: in
        action: block
        localport: all
        protocol: all

    - name: Disable Windows Firewall
      win_service:
        name: MpsSvc
        start_mode: disabled
        state: stopped
