---
- name: Disable Windows Firewall for all profiles
  hosts: all
  gather_facts: yes
  tasks:
    - name: Disable Windows Firewall for Domain profile
      win_shell: |
        Set-NetFirewallProfile -Profile Domain -Enabled False

    - name: Disable Windows Firewall for Private profile
      win_shell: |
        Set-NetFirewallProfile -Profile Private -Enabled False

    - name: Disable Windows Firewall for Public profile
      win_shell: |
        Set-NetFirewallProfile -Profile Public -Enabled False

    - name: Confirm Windows Firewall status for all profiles
      win_shell: |
        Get-NetFirewallProfile | Select-Object Name, Enabled
      register: firewall_status

    - name: Display Firewall status
      debug:
        msg: "{{ firewall_status.stdout }}"
